plugins:
  - jekyll-multiple-languages-plugin

exclude:
  # SRC
  - src
  # Informació
  - LICENCE.md
  - README.md
  # Gestors de paquets
  ## Bundle
  - Gemfile
  - Gemfile.lock
  ## Node (npm)
  - node_modules
  - package.json
  - package-lock.json

url: ""
baseurl: ""
permalink: /:title/

languages: ["ca", "es"]
exclude_from_localizations: ["assets"]
languageNames:
  ca: "Català"
  es: "Español"
