plugins:
  - jekyll-multiple-languages-plugin

exclude:
  # SRC
  - src
  # Informació
  - LICENCE.md
  - README.md
  # Gestors de paquets
  ## Bundle
  - Gemfile
  - Gemfile.lock
  ## Node (npm)
  - node_modules
  - package.json
  - package-lock.json
  # Gulp (task runner)
  - gulpfile.js

url: "http://senzill.dev/_site/"
baseurl: ""
permalink: /:title/

languages: ["ca", "es"]
exclude_from_localizations: ["assets"]
languageNames:
  ca: "Català"
  es: "Español"

pwa:
  manifest:
    name: "Senzill"
    short_name: "Senzill"
    theme_color: "#0b1728"
    background_color: "#afc6e9"
  sw_cache:
    - "/"
    - "/assets/"
    - "/offline/index.html"

legal:
  owner:
    name: ""
    id: ""
    domicile: ""
    email: ""
    domain: "senzill.dev"
  developer:
    name: "IlercApp"
