# Configuració
# ------------------------------------------------------------------------------
exclude:
  # SRC
  - src
  # Informació
  - LICENCE.md
  - README.md
  # Gestors de paquets
  ## Bundle
  - Gemfile
  - Gemfile.lock
  ## Node (npm)
  - node_modules
  - package.json
  - package-lock.json
  # Gulp (task runner)
  - gulpfile.js

# Lloc Web
# ------------------------------------------------------------------------------
url: "http://senzill.oo"
baseurl: "/_site"

# Idiomes
# ------------------------------------------------------------------------------
langs:
  - "ca"
  - "es"

t:
  default_lang: "ca"
  ca:
    site_info:
      name: "Senzill"
      motto: "Per Roger Forner Fabre"
      locale: "ca-es"
      geo_tag:
        region: "ES-CT"
        placename: "Tortosa"
        position: "40.812578;0.521442"
        icbm: "40.812578, 0.521442"
    open_graph:
      facebook:
        app_id:
        publisher: #https://www.facebook.com/compteLLocWeb
        author: #https://www.facebook.com/compteAutorRa
        img:
      google_plus:
        publisher: #https://plus.google.com/compteLLocWeb
        author: #https://plus.google.com/compteAutorRa
        img:
      twitter:
        publisher: #@compteLlocWeb
        author: "@rogerforner" #@compteAutorRa
        img:
  es:
    site_info:
      name: "Senzill"
      motto:
      locale: "es-es"
      geo_tag:
        region:
        placename:
        position:
        icbm:
    open_graph:
      facebook:
        app_id:
        publisher: #https://www.facebook.com/compteLLocWeb
        author: #https://www.facebook.com/compteAutorRa
        img:
      google_plus:
        publisher: #https://plus.google.com/compteLLocWeb
        author: #https://plus.google.com/compteAutorRa
        img:
      twitter:
        publisher: #@compteLlocWeb
        author: #@compteAutorRa
        img:

# Tipus de publicacions
# ------------------------------------------------------------------------------
collections:
  pages:
    output: true
  posts:
    output: true

# URLs permanents
# ------------------------------------------------------------------------------
permalink: "pretty"

defaults:
  - # Pàgines
    scope:
      path: "_pages/ca"
    values:
      permalink: "/ca/:title"
      lang: "ca"
      layout: "default"
  -
    scope:
      path: "_pages/es"
    values:
      permalink: "/es/:title"
      lang: "es"
      layout: "default"
  - # Publicacions
    scope:
      path: "_posts/ca"
    values:
      permalink: "/ca/posts/:title"
      lang: "ca"
      layout: "default"
  -
    scope:
      path: "_posts/es"
    values:
      permalink: "/es/posts/:title"
      lang: "es"
      layout: "default"


# Progressive Web App
# ------------------------------------------------------------------------------
pwa:
  manifest:
    name: "Senzill"
    short_name: "Senzill"
    theme_color: "#0b1728"
    background_color: "#afc6e9"
  sw_cache:
    - "/"
    - "/assets/"
    - "/offline/index.html"

# Informació legal
# ------------------------------------------------------------------------------
legal:
  owner:
    name:
    id:
    domicile:
    email:
    domain: "senzill.dev"
  developer:
    name: "IlercApp"
